version: '3.6'
services:
  clamav:
    container_name: "ddev-${DDEV_SITENAME}-clamav"
    image: clamav/clamav:1.0
    networks: [default, ddev_default]
    volumes:
      - "../:/scandir"
      - ".:/mnt/ddev_config"
    expose:
      - 3310
      - 7357
    labels:
      com.ddev.site-name: ${DDEV_SITENAME}
      com.ddev.approot: $DDEV_APPROOT
